### ISSUE TITLE
The project isn't running!

### ISSUE THREAD

**Issue by devmike123** [DevMike123/Jarvis#2]
The project isn't starting, do I need to install some more packages to run the package!

**Comment by DevMike123** [comment]
Thanks for taking time contrbuting to the project! I hope you have triggered some issue while using project! Do not worry, we will resolve it as soon as possible! Also, you can check out other issues if you want more help!

**Comment by devmike123** [comment]
You need to install Microsoft VSC Build Tools into the VSCode Software to run this project and enable speech recognition!  I hope you're issue has been resolved!
